### ISSUE TITLE
Rendering Code for Evaluation

### ISSUE THREAD

**Issue by Friedrich-M** [yanqinJiang/Consistent4D#12]
Could you kindly provide the rendering code for evaluation?

**Comment by yanqinJiang** [comment]
Sorry for the late reply. 
The readme.txt in test data says, 
```txt
We capture the input data with a static camera set at an azimuth angle of 0°. 
For evaluation, we generate four distinct views at azimuth angles of -75°, 15°, 105°, and 195°, respectively. (No modifications to elevation, radius, and other camera parameters.)
```

So, in training config, you could modify `data.random_camera.n_val_views` to `24`, and set `data.eval_timestamp` to `[]`, `data.eval_pose_index` to `[1, 7, 13, 19]` , and then run standard validation process to get evaluation renderings.

The above evaluation config setting is not tested because my code is on old machine and I cannot get access to it now. You can have a try and then compare the results with the rendering results provided by us.

If you meet any problem, feel free to let me know 😄

**Comment by Friedrich-M** [comment]
Thank you so much for your help!
